// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Crypto: typeof import('./src/components/Crypto.vue')['default']
    CryptoCurrency: typeof import('./src/components/CryptoCurrency.vue')['default']
    CryptoCurrency_Card: typeof import('./src/components/CryptoCurrency_Card.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    PreLoader: typeof import('./src/components/PreLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
