// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CryptoCurrency_Card: typeof import('./src/components/CryptoCurrency_Card.vue')['default']
    Echart: typeof import('./src/components/echart.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    KLineChart: typeof import('./src/components/KLineChart.vue')['default']
    MarketCap: typeof import('./src/components/MarketCap.vue')['default']
    Percent: typeof import('./src/components/Percent.vue')['default']
    PreLoader: typeof import('./src/components/PreLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
